name: tests-payments

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
      - run: cd payments && npm install && export STRIPE_KEY = ${{ secrets.STRIPE_KEY }} && npm run test:ci
